//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_IDE_Avalonia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AI-IDE-Avalonia.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Chat.
        /// </summary>
        public static string AiChatTitle {
            get {
                return ResourceManager.GetString("AiChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new file..
        /// </summary>
        public static string BsNew {
            get {
                return ResourceManager.GetString("BsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing file..
        /// </summary>
        public static string BsOpen {
            get {
                return ResourceManager.GetString("BsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current file..
        /// </summary>
        public static string BsSave {
            get {
                return ResourceManager.GetString("BsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all open files..
        /// </summary>
        public static string BsSaveAll {
            get {
                return ResourceManager.GetString("BsSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ChatClear {
            get {
                return ResourceManager.GetString("ChatClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        public static string ChatModelLabel {
            get {
                return ResourceManager.GetString("ChatModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider:.
        /// </summary>
        public static string ChatProviderLabel {
            get {
                return ResourceManager.GetString("ChatProviderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ChatSend {
            get {
                return ResourceManager.GetString("ChatSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ChatStop {
            get {
                return ResourceManager.GetString("ChatStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool call.
        /// </summary>
        public static string ChatToolCall {
            get {
                return ResourceManager.GetString("ChatToolCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Without Workspace.
        /// </summary>
        public static string ContinueWithoutWorkspace {
            get {
                return ResourceManager.GetString("ContinueWithoutWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CtxAdd {
            get {
                return ResourceManager.GetString("CtxAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Existing File....
        /// </summary>
        public static string CtxAddExistingFile {
            get {
                return ResourceManager.GetString("CtxAddExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CtxCopy {
            get {
                return ResourceManager.GetString("CtxCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Full Path.
        /// </summary>
        public static string CtxCopyFullPath {
            get {
                return ResourceManager.GetString("CtxCopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CtxCut {
            get {
                return ResourceManager.GetString("CtxCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CtxDelete {
            get {
                return ResourceManager.GetString("CtxDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File....
        /// </summary>
        public static string CtxNewFile {
            get {
                return ResourceManager.GetString("CtxNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder....
        /// </summary>
        public static string CtxNewFolder {
            get {
                return ResourceManager.GetString("CtxNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string CtxOpen {
            get {
                return ResourceManager.GetString("CtxOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing Folder.
        /// </summary>
        public static string CtxOpenContainingFolder {
            get {
                return ResourceManager.GetString("CtxOpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string CtxPaste {
            get {
                return ResourceManager.GetString("CtxPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties....
        /// </summary>
        public static string CtxProperties {
            get {
                return ResourceManager.GetString("CtxProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string CtxRename {
            get {
                return ResourceManager.GetString("CtxRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string FilterWatermark {
            get {
                return ResourceManager.GetString("FilterWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string GroupBuild {
            get {
                return ResourceManager.GetString("GroupBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string GroupClipboard {
            get {
                return ResourceManager.GetString("GroupClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string GroupDebug {
            get {
                return ResourceManager.GetString("GroupDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string GroupFile {
            get {
                return ResourceManager.GetString("GroupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string GroupFind {
            get {
                return ResourceManager.GetString("GroupFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string GroupHistory {
            get {
                return ResourceManager.GetString("GroupHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string GroupLanguage {
            get {
                return ResourceManager.GetString("GroupLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string GroupLayout {
            get {
                return ResourceManager.GetString("GroupLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string GroupNavigate {
            get {
                return ResourceManager.GetString("GroupNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panels.
        /// </summary>
        public static string GroupPanels {
            get {
                return ResourceManager.GetString("GroupPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string GroupSupport {
            get {
                return ResourceManager.GetString("GroupSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string GroupThemes {
            get {
                return ResourceManager.GetString("GroupThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string GroupWindows {
            get {
                return ResourceManager.GetString("GroupWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ItemAbout {
            get {
                return ResourceManager.GetString("ItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ItemBack {
            get {
                return ResourceManager.GetString("ItemBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string ItemBuild {
            get {
                return ResourceManager.GetString("ItemBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string ItemClean {
            get {
                return ResourceManager.GetString("ItemClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ItemClose {
            get {
                return ResourceManager.GetString("ItemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ItemComment {
            get {
                return ResourceManager.GetString("ItemComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ItemCopy {
            get {
                return ResourceManager.GetString("ItemCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string ItemCut {
            get {
                return ResourceManager.GetString("ItemCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string ItemDashboard {
            get {
                return ResourceManager.GetString("ItemDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Windows.
        /// </summary>
        public static string ItemExitWindows {
            get {
                return ResourceManager.GetString("ItemExitWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string ItemExplorer {
            get {
                return ResourceManager.GetString("ItemExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string ItemFind {
            get {
                return ResourceManager.GetString("ItemFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ItemForward {
            get {
                return ResourceManager.GetString("ItemForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        public static string ItemGoTo {
            get {
                return ResourceManager.GetString("ItemGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ItemHome {
            get {
                return ResourceManager.GetString("ItemHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ItemLanguage {
            get {
                return ResourceManager.GetString("ItemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ItemNew {
            get {
                return ResourceManager.GetString("ItemNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layout.
        /// </summary>
        public static string ItemNewLayout {
            get {
                return ResourceManager.GetString("ItemNewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ItemOpen {
            get {
                return ResourceManager.GetString("ItemOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Layout.
        /// </summary>
        public static string ItemOpenLayout {
            get {
                return ResourceManager.GetString("ItemOpenLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string ItemPaste {
            get {
                return ResourceManager.GetString("ItemPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        public static string ItemProblems {
            get {
                return ResourceManager.GetString("ItemProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string ItemRebuild {
            get {
                return ResourceManager.GetString("ItemRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string ItemRedo {
            get {
                return ResourceManager.GetString("ItemRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ItemReplace {
            get {
                return ResourceManager.GetString("ItemReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string ItemRestart {
            get {
                return ResourceManager.GetString("ItemRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ItemSave {
            get {
                return ResourceManager.GetString("ItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string ItemSaveAll {
            get {
                return ResourceManager.GetString("ItemSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Layout.
        /// </summary>
        public static string ItemSaveLayout {
            get {
                return ResourceManager.GetString("ItemSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  items.
        /// </summary>
        public static string ItemsCount {
            get {
                return ResourceManager.GetString("ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Windows.
        /// </summary>
        public static string ItemShowWindows {
            get {
                return ResourceManager.GetString("ItemShowWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ItemStart {
            get {
                return ResourceManager.GetString("ItemStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ItemStop {
            get {
                return ResourceManager.GetString("ItemStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        public static string ItemTerminal {
            get {
                return ResourceManager.GetString("ItemTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ItemTheme {
            get {
                return ResourceManager.GetString("ItemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Theme.
        /// </summary>
        public static string ItemToggleTheme {
            get {
                return ResourceManager.GetString("ItemToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomment.
        /// </summary>
        public static string ItemUncomment {
            get {
                return ResourceManager.GetString("ItemUncomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string ItemUndo {
            get {
                return ResourceManager.GetString("ItemUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string LoadingPlaceholder {
            get {
                return ResourceManager.GetString("LoadingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent workspaces.
        /// </summary>
        public static string NoRecentWorkspaces {
            get {
                return ResourceManager.GetString("NoRecentWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder….
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  selected.
        /// </summary>
        public static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TabEdit {
            get {
                return ResourceManager.GetString("TabEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string TabHelp {
            get {
                return ResourceManager.GetString("TabHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string TabRun {
            get {
                return ResourceManager.GetString("TabRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string TabView {
            get {
                return ResourceManager.GetString("TabView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string TipAbout {
            get {
                return ResourceManager.GetString("TipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string TipBack {
            get {
                return ResourceManager.GetString("TipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build the project.
        /// </summary>
        public static string TipBuild {
            get {
                return ResourceManager.GetString("TipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean build outputs.
        /// </summary>
        public static string TipClean {
            get {
                return ResourceManager.GetString("TipClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the current dock layout.
        /// </summary>
        public static string TipCloseLayout {
            get {
                return ResourceManager.GetString("TipCloseLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment selected lines.
        /// </summary>
        public static string TipComment {
            get {
                return ResourceManager.GetString("TipComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string TipCopy {
            get {
                return ResourceManager.GetString("TipCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut to clipboard.
        /// </summary>
        public static string TipCut {
            get {
                return ResourceManager.GetString("TipCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dashboard.
        /// </summary>
        public static string TipDashboard {
            get {
                return ResourceManager.GetString("TipDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit floating windows mode.
        /// </summary>
        public static string TipExitWindows {
            get {
                return ResourceManager.GetString("TipExitWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Solution Explorer.
        /// </summary>
        public static string TipExplorer {
            get {
                return ResourceManager.GetString("TipExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in current file.
        /// </summary>
        public static string TipFind {
            get {
                return ResourceManager.GetString("TipFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward.
        /// </summary>
        public static string TipForward {
            get {
                return ResourceManager.GetString("TipForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to line or symbol.
        /// </summary>
        public static string TipGoTo {
            get {
                return ResourceManager.GetString("TipGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to home view.
        /// </summary>
        public static string TipHome {
            get {
                return ResourceManager.GetString("TipHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch application language.
        /// </summary>
        public static string TipLanguage {
            get {
                return ResourceManager.GetString("TipLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new file.
        /// </summary>
        public static string TipNew {
            get {
                return ResourceManager.GetString("TipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new dock layout.
        /// </summary>
        public static string TipNewLayout {
            get {
                return ResourceManager.GetString("TipNewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file.
        /// </summary>
        public static string TipOpen {
            get {
                return ResourceManager.GetString("TipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a saved dock layout.
        /// </summary>
        public static string TipOpenLayout {
            get {
                return ResourceManager.GetString("TipOpenLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        public static string TipPaste {
            get {
                return ResourceManager.GetString("TipPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Problems panel.
        /// </summary>
        public static string TipProblems {
            get {
                return ResourceManager.GetString("TipProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build project.
        /// </summary>
        public static string TipQatBuild {
            get {
                return ResourceManager.GetString("TipQatBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string TipQatSave {
            get {
                return ResourceManager.GetString("TipQatSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle dark/light theme.
        /// </summary>
        public static string TipQatTheme {
            get {
                return ResourceManager.GetString("TipQatTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last action.
        /// </summary>
        public static string TipQatUndo {
            get {
                return ResourceManager.GetString("TipQatUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild the project.
        /// </summary>
        public static string TipRebuild {
            get {
                return ResourceManager.GetString("TipRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo last undone action.
        /// </summary>
        public static string TipRedo {
            get {
                return ResourceManager.GetString("TipRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace.
        /// </summary>
        public static string TipReplace {
            get {
                return ResourceManager.GetString("TipReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart debugging.
        /// </summary>
        public static string TipRestart {
            get {
                return ResourceManager.GetString("TipRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current file.
        /// </summary>
        public static string TipSave {
            get {
                return ResourceManager.GetString("TipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all open files.
        /// </summary>
        public static string TipSaveAll {
            get {
                return ResourceManager.GetString("TipSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current dock layout.
        /// </summary>
        public static string TipSaveLayout {
            get {
                return ResourceManager.GetString("TipSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all floating windows.
        /// </summary>
        public static string TipShowWindows {
            get {
                return ResourceManager.GetString("TipShowWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start debugging.
        /// </summary>
        public static string TipStart {
            get {
                return ResourceManager.GetString("TipStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop debugging.
        /// </summary>
        public static string TipStop {
            get {
                return ResourceManager.GetString("TipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Terminal panel.
        /// </summary>
        public static string TipTerminal {
            get {
                return ResourceManager.GetString("TipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomment selected lines.
        /// </summary>
        public static string TipUncomment {
            get {
                return ResourceManager.GetString("TipUncomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last action.
        /// </summary>
        public static string TipUndo {
            get {
                return ResourceManager.GetString("TipUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string ToolSolutionExplorer {
            get {
                return ResourceManager.GetString("ToolSolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a recent folder or open a new one on your machine.
        /// </summary>
        public static string WorkspaceSelectorSubtitle {
            get {
                return ResourceManager.GetString("WorkspaceSelectorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Workspace.
        /// </summary>
        public static string WorkspaceSelectorTitle {
            get {
                return ResourceManager.GetString("WorkspaceSelectorTitle", resourceCulture);
            }
        }
    }
}
